[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyplimstex"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "scikit-learn"
]

[project.scripts]
pyplimstex = "pyplimstex.main:cli"